baseURL: https://example.com
title: Awesome title

languageCode: en
defaultContentLanguage: en

# disableKinds:
#   - taxonomy
#   - terms
#   - categories

# ignoreErrors:
#   - error-disable-taxonomy

params:
  favicon: /path/to/favicon

  homepage:
    overwrite: false
    url: /blog/

  # Bottom right menu SVG
  menu:
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>'
  
  # Dark and light mode theming
  theming: 
    enabled: true
    lightIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sun"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>'
    darkIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-moon"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>'

  # Language selection will also only appear if the given page has at least one translation
  languages:
    enabled: true

  # Versioning can be enabled to handle pages versions (per language). It does not handle site versions.
  # To have it work, just create a new page in version folder (for instance 0.1/index.md) under the given section (for instance /my-post/_index.md).
  # For the section, set the parameter 'version', goes the same for the page.
  versioning:
    enabled: true
    prefix: v # The visual prefix to add on menu

  # Great to prefetch the next page is user is gonna go to (listen to mouse events on links)
  # https://instant.page/
  instantPage:
    enabled: true
    version: 5.2.0

  # Associated to 'lazyload' CSS class, it's a great tool
  # https://afarkas.github.io/lazysizes/
  lazysizes:
    enabled: true

  # Bootstrap cannot be disabled as it's the main front framework used
  bootstrap:
    version: 5.3.0

  # Additional head css files and js files. Those must be in assets folder
  header:
    css: []
    js: []
    scss: []

  # Additional footer css files and js files. Those must be in assets folder
  footer:
    css: []
    js: []
    scss: []